# Usa una imagen de Nginx para servir archivos estáticos (Frontend)
FROM nginx:alpine

# Copia el contenido de la carpeta frontend al directorio de Nginx
COPY . /usr/share/nginx/html

# Puerto por defecto de Nginx
EXPOSE 80